### ISSUE TITLE
Playlist/queue functionality

### ISSUE THREAD

**Issue by dwhinham** [dwhinham/OSXMP#1]
The app should allow you to queue up a bunch of files and listen to them in sequence.

We should investigate standard playlist file formats like .M3U and so on.

**Comment by echolevel** [comment]
Sounds good. Do existing formats allow for per-track repeat count directives? It would be nice to have more granular control over that than just a global "repeat n times after loop detected", though that option (a la XMplay) is also very handy.

**Comment by dwhinham** [comment]
It looks like the PLS and M3U file formats allows `LengthX` and `EXTINF` directives which store the runtime in seconds, which we could count up to and then advance the playlist. But custom fields or extra data don't seem to be a thing in those formats.

We could come up with our own playlist format, maybe even just use YAML which can store anything we want, and would be convertible to other formats easily:

```
playlist:
  - path:   ~/modules/alloyrun.xm
    title:  Alloy Run
    repeat: 2

  - path:   ~/modules/cream_of_the_earth.mod
    title:  Cream of the Earth
    repeat: 1

  - path:   ~/modules/r-light.xm
    title:  Lightspeed Travel
    repeat: 0
```
